name: build

on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        arch: ["x86", "x64"]	
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: devenv Document\\EDCB_ALL.VS2015.sln /rebuild Release|${{ matrix.value }} 

