name: build

on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        arch: ["Win32", "x64"]	
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild Document\EDCB_ALL.VS2015.sln -t:Rebuild -p:Configuration=Release -p:platform=${{ matrix.value }} 

