name: build

on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        platform:
          - value: Win32
            path: x86
          - value: x64
            path: x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild Document\EDCB_ALL.VS2015.sln -t:Rebuild -p:Configuration=Release -p:platform=${{ matrix.platform.value }}
      - run: |
          tag=$(basename "${{ github.ref }}")_$(date +%Y%m%d.%H%M%S)
          echo "tag=$tag" >> $GITHUB_ENV
      - uses: thedoctor0/zip-release@master
        with:
          path: ${{ matrix.platform.path }}/Release/
          filename: EDCB-${{ matrix.platform.path }}-${{ env.tag }}.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          prerelease: true
          files: |
            EDCB-${{ matrix.platform.path }}-${{ env.tag }}.zip
